name: Node.js CI

on: [push]

jobs:
  build:
    name: Build

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x, 13.x]
        mode: [production, development]

    runs-on: ${{ matrix.os }}
    env:
      NODE_ENV: ${{ matrix.mode }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci --no-optional
      env:
        NODE_ENV: development
    - run: npm run dist
    - run: npm run lint
    - run: npm test
