name: Node.js CI

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '**' # Ignore tag push.

jobs:
  test:
    name: Test

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12.x, 13.x]

    runs-on: ${{ matrix.os }}
    env:
      NODE_ENV: development

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
    - run: npm run compile
    - run: npm test
  release:
    if: github.ref == 'refs/heads/master'
    needs: test
    name: Release ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      NODE_ENV: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
      env:
        NODE_ENV: development
    - run: npm run dist
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
